# Generated by Django 5.2.1 on 2025-05-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='alt_spellings',
            field=models.JSONField(blank=True, help_text='Alternative spellings', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='borders',
            field=models.JSONField(blank=True, help_text='List of cca3 codes of bordering countries', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='capital_info',
            field=models.JSONField(blank=True, help_text='Capital coordinates', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='car',
            field=models.JSONField(blank=True, help_text='Car signs and side of road', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='coat_of_arms_png_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Coat of Arms PNG'),
        ),
        migrations.AddField(
            model_name='country',
            name='coat_of_arms_svg_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Coat of Arms SVG'),
        ),
        migrations.AddField(
            model_name='country',
            name='continents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='demonyms',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='fifa',
            field=models.CharField(blank=True, help_text='FIFA country code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='gini',
            field=models.JSONField(blank=True, help_text='Gini coefficient by year', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='idd',
            field=models.JSONField(blank=True, help_text='International direct dialing info', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='independent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='landlocked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='latlng',
            field=models.JSONField(blank=True, help_text='Latitude and Longitude', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='maps',
            field=models.JSONField(blank=True, help_text='Links to Google Maps and OpenStreetMaps', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='postal_code',
            field=models.JSONField(blank=True, help_text='Postal code format and regex', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='start_of_week',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='timezones',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='tld',
            field=models.JSONField(blank=True, help_text='Top-level domain(s)', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='translations',
            field=models.JSONField(blank=True, help_text='Country name translations', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='un_member',
            field=models.BooleanField(blank=True, null=True, verbose_name='UN Member'),
        ),
    ]
